site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Blogs: blog.md
    - Documentacion iaw: documentacion.md

theme: 
    name: material
    language: en
    palette: 
        primary: deep purple
        accent: orange
    font:
        text: Anta
